### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jlew715/rails_proj2#1]
[The project](http://codekwondo.herokuapp.com/showcases/585) actually specifies that:

> You can build a model for anything you'd like, _except_ for recyclers.

Can you update this with another model?

**Comment by jlew715** [comment]
Whoops! Sometimes I read over things too fast. All fixed now!

**Comment by chrisvfritz** [comment]
Much better. I'd just like one more validation added now, for number of locations. I was able to enter a negative number, which probably isn't desirable. See if [this resource](http://stackoverflow.com/questions/4416278/how-to-implement-min-max-validator-in-rails-3) helps you figure out how you can prevent negative numbers, perhaps including 0, depending on what you think is logical for this system.

**Comment by jlew715** [comment]
fixed

**Comment by chrisvfritz** [comment]
:+1: Fantastic!
